# Generated by Django 5.0.6 on 2024-05-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('doc_id', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
